# Generated by Django 6.1.1 on 2026-10-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Completed', 'Completed')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactenquiry',
            name='service',
            field=models.CharField(choices=[('Website', 'Website'), ('Mobile App', 'Mobile App'), ('Web Application', 'Web Application'), ('E-commerce', 'E-commerce'), ('Product Development', 'Product Development'), ('Other', 'Other')], max_length=100),
        ),
    ]
